---

- name: APT | Install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - git

- name: Extract latest tag number
  when: wkhtmltopdf_tag == "latest"
  block:

  - name: Fetch latest wkhtmltopdf tag
    ansible.builtin.shell: >
      set -o pipefail && \
      git ls-remote --tags https://github.com/wkhtmltopdf/packaging.git | cut -d/ -f3- | tail -n1
    args:
      executable: /bin/bash
    register: latest_wkhtmltopdf_tag
    changed_when: false

  - name: Set wkhtmltopdf_tag
    ansible.builtin.set_fact:
      wkhtmltopdf_tag: "{{ latest_wkhtmltopdf_tag.stdout }}"

- name: Download wkhtmltopdf package for Linux arm64
  ansible.builtin.get_url:
    url: "https://github.com/wkhtmltopdf/packaging/releases/download/{{ wkhtmltopdf_tag }}/wkhtmltox_{{ wkhtmltopdf_tag }}.{{ ansible_distribution_release }}_arm64.deb"
    dest: /tmp/wkhtmltopdf.deb
    mode: '0644'
  when: "'aarch64' in ansible_architecture and 'Linux' == ansible_system"

- name: Download wkhtmltopdf package for Linux amd64
  ansible.builtin.get_url:
    url: "https://github.com/wkhtmltopdf/packaging/releases/download/{{ wkhtmltopdf_tag }}/wkhtmltox_{{ wkhtmltopdf_tag }}.{{ ansible_distribution_release }}_amd64.deb"
    dest: /tmp/wkhtmltopdf.deb
    mode: '0644'
  when: "'x86_64' in ansible_architecture and 'Linux' == ansible_system"

- name: Install wkhtmltopdf
  ansible.builtin.apt:
    deb: "/tmp/wkhtmltopdf.deb"

- name: Install google fonts
  when: wkhtmltopdf_install_google_fonts
  block:

  - name: APT | Install dependencies
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: true
      autoremove: true
      update_cache: true
      cache_valid_time: 3600
    vars:
      packages:
      - unzip
      - findutils

  - name: Fetching google fonts
    ansible.builtin.get_url:
      url: "https://github.com/google/fonts/archive/main.zip"
      dest: /tmp/googlefonts.zip
      mode: '0644'
      force: false

  - name: Create google fonts opt directory
    ansible.builtin.file:
      path: /opt/googlefonts
      state: directory
      mode: '0644'

  - name: Unarchive google fonts
    ansible.builtin.unarchive:
      src: /tmp/googlefonts.zip
      dest: /opt/googlefonts
      remote_src: true

  - name: Create google fonts target directory
    ansible.builtin.file:
      path: /usr/share/fonts/truetype/google-fonts
      state: directory
      mode: '0755'

  - name: Install google fonts
    ansible.builtin.shell: |
      set -o pipefail && find /opt/googlefonts/ -name "*.ttf" |  xargs -I{} cp {} /usr/share/fonts/truetype/google-fonts/
      chmod -R 644 /usr/share/fonts/truetype/google-fonts/*
      fc-cache -f > /dev/null
    args:
      executable: /bin/bash
      creates: /usr/share/fonts/truetype/google-fonts/*

...
