---

- name: APT | Install wkhtmltopdf
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - wkhtmltopdf

- name: Install google fonts
  when: wkhtmltopdf_install_google_fonts
  block:

  - name: APT | Install dependencies
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: true
      autoremove: true
      update_cache: true
      cache_valid_time: 3600
    vars:
      packages:
      - git
      - unzip
      - findutils

  - name: Fetching google fonts
    ansible.builtin.get_url:
      url: "https://github.com/google/fonts/archive/main.zip"
      dest: /tmp/googlefonts.zip
      mode: '0644'
      force: false

  - name: Create google fonts opt directory
    ansible.builtin.file:
      path: /opt/googlefonts
      state: directory
      mode: '0644'

  - name: Unarchive google fonts
    ansible.builtin.unarchive:
      src: /tmp/googlefonts.zip
      dest: /opt/googlefonts
      remote_src: true
      creates: /opt/googlefonts/fonts-main

  - name: Install google fonts
    ansible.builtin.shell: |
      set -o pipefail && find /opt/googlefonts/ -name "*.ttf" |  xargs -I{} cp {} /usr/share/fonts/truetype/google-fonts/
      mkdir /usr/share/fonts/truetype/google-fonts
      chmod 755 /usr/share/fonts/truetype/google-fonts
      chmod -R 644 /usr/share/fonts/truetype/google-fonts/*
      fc-cache -f > /dev/null
    args:
      executable: /bin/bash
      creates: /usr/share/fonts/truetype/google-fonts

...
