---
- hosts: all
  become: true
  become_method: sudo

  vars:
    # wkhtmltopdf_patch_release: "x.x.x"
    # wkhtmltopdf_full_release: "x.x.x.x-x"
    # wkhtmltopdf_install_google_fonts: false
    wkhtmltopdf_install_google_fonts: true

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-wkhtmltopdf
...
