---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    # wkhtmltopdf_tag: "x.x.x.x-x"
    wkhtmltopdf_install_google_fonts: true
  tasks:
  - name: Include andrelohmann.wkhtmltopdf
    ansible.builtin.include_role:
      name: "andrelohmann.wkhtmltopdf"
...
