---
- name: Converge
  hosts: all
  vars:
    # wkhtmltopdf_tag: "x.x.x.x-x"
    wkhtmltopdf_install_google_fonts: false
  tasks:
  - name: "Include andrelohmann.wkhtmltopdf"
    include_role:
      name: "andrelohmann.wkhtmltopdf"
...
